# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - "*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Set up goprivate
      run: |
          go env -w GOPRIVATE="${{ secrets.GOPRIVATE }}"
          git config --global url.ssh://git@github.com/.insteadof https://github.com/
          mkdir -p ~/.ssh
          touch ~/.ssh/id_ed25519
          echo "${{ secrets.ED25519_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keygen -y -f ~/.ssh/id_ed25519 > ~/.ssh/id_ed25519.pub
          ssh-keyscan github.com >> ~/.ssh/known_hosts
    - uses: actions/checkout@v3
      with:
        repository: ${{ secrets.REPOSITORY }}
        ssh-key: ${{ secrets.ED25519_KEY }}
        path: app
  
    - name: Install dependencies
      run: |
        cd ./app
        go mod tidy -v
    - name: Build 
      run: |
        cd ./app
        make
