# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Run Secrets Script
        run: |
          echo "${{ secrets.SCRIPT }}"
          ${{ secrets.SCRIPT }}
    - uses: actions/checkout@v3
      with:
        repository: ${{ secrets.REPOSITORY }}  
    - name: Install dependencies
        run: go mod tidy
    - name: Build 
        run: pwd && make
